// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngneunjtgeqnkendllyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nbmV1bmp0Z2VxbmtlbmRsbHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTAxNTMsImV4cCI6MjA3MTc4NjE1M30.fiqUoo4Sq2KzUAEJkBX5Ay7T2XihbcpsQNQR5HWXNjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});